CREATE TABLE MEMBER (
	USERID	VARCHAR2(8)		PRIMARY KEY,
	USERPWD	VARCHAR2(10)	NOT NULL
);

INSERT INTO MEMBER 
VALUES ('candy', '1234')
;
INSERT INTO MEMBER
VALUES ('admin', '5678')
;

CREATE TABLE BOOKSHOP (
	ISBN	VARCHAR2(15)	PRIMARY KEY,
	TITLE	VARCHAR2(50)	NOT NULL,
	AUTHOR	VARCHAR2(10)	NOT	NULL,
	COMPANY	VARCHAR2(50),
	PRICE	NUMBER
);

INSERT INTO BOOKSHOP 
VALUES ('88-90-11', '오라클 3일완성', '이오라', '야메루출판사', '15000')
;
INSERT INTO BOOKSHOP
VALUES ('90-10-12', 'JSP 달인되기', '송JP', '공갈닷컴', '20000')
;
INSERT INTO BOOKSHOP
VALUES ('87-90-33', '자바무따기', '김자바', '디지탈박스', '35000')
;

SELECT * FROM BOOKSHOP
;

DROP TABLE MEMBER
;
DROP TABLE BOOKSHOP
;
DROP TABLE BOOK
;
DROP TABLE BOOKORDER
;